require('./map-test.js')
require('./keyboard-test.js')
require('./player-test.js')
require('./ball-collisions-test.js')
require('./flag-collisions-test.js')
require('./spike-test.js')
require('./spike-collisions-test.js')
require('./map-blueprint-test.js')
